apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-app
  name: hello-app1
  annotations:
    link.argocd.argoproj.io/external-link: https://hub.docker.com/repository/docker/vidising
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: hello-app1
        image: vidising/hello-app:v3
        imagePullPolicy: Always
